### ISSUE TITLE
conda: reduce size by deleting unecessary packages

### ISSUE THREAD

**Issue by looooo** [FreeCAD/FreeCAD-AppImage#24]
installed but (most likely) not needed
- [x] llvm-dev
- [x] clang-dev

further size reduction wanted

**Comment by triplus** [comment]
Reference:
https://forum.freecadweb.org/viewtopic.php?f=42&t=39138#p332305

**Comment by triplus** [comment]
Done: https://github.com/FreeCAD/FreeCAD-AppImage/commit/474c705617efee353ef09f272c8f40b5376c06eb

Rationale: https://forum.freecadweb.org/viewtopic.php?f=42&t=39138&p=338590#p338590

Closing the issue report.
