### ISSUE TITLE
No windows dev build - only time+date in SHA256 file

### ISSUE THREAD

**Issue by jpnielsen** [FreeCAD/FreeCAD-AppImage#39]
There's no 0.19_pre windows release available.

https://github.com/FreeCAD/FreeCAD/releases/download/0.19_pre/FreeCAD_.0.10-Win-Conda_vc14.x-x86_64.7z-SHA256.txt only has "Thu 09/17/2020-21:55:57.30" in it.

Best regards, and thanks.

**Comment by sgrogan** [comment]
Fixed, caused by github timeout
