### ISSUE TITLE
cmdline arguments not passed to FreeCAD

### ISSUE THREAD

**Issue by Grawp** [FreeCAD/FreeCAD-AppImage#9]
https://github.com/FreeCAD/FreeCAD-AppImage/blob/5bc472e3750c949a812127074cf490a4904d989b/conda/AppDir/AppRun#L10

Please modify the line to something like this
```bash
${HERE}/usr/bin/FreeCAD "$@"
```
so one can pass arguments to the FreeCAD e.g. a file to open etc...

**Comment by triplus** [comment]
Done.

P.S. Next time best to create a PR, to better credit the contribution.
